#!/opt/homebrew/bin/bash
set -e

ADDON_DIR="$(cd "$(dirname "$0")" && pwd)"
INSTALL_DIR="$HOME/.wifi-loc-control"

# ── gum ───────────────────────────────────────────────────────────────────────
if ! command -v gum &>/dev/null; then
    echo "Installing gum..."
    brew install gum
fi
GUM=$(which gum)

ok()   { $GUM style --foreground 2   "✓ $*"; }
warn() { $GUM style --foreground 214 "⚠ $*"; }
err()  { $GUM style --foreground 1   "✗ $*"; }
info() { $GUM style --foreground 12  "→ $*"; }

_GUM_TMP=$(mktemp)
trap 'rm -f "$_GUM_TMP"' EXIT

drain_tty() {
    stty -echo </dev/tty 2>/dev/null
    sleep 0.3
    while IFS= read -r -t 0.1 -n 1 _d </dev/tty 2>/dev/null; do :; done
    stty echo </dev/tty 2>/dev/null
}

choose_one() {
    local prompt="$1"; shift
    [[ -n "$prompt" ]] && printf '\033[38;5;212m%s\033[0m\n' "$prompt" >/dev/tty
    drain_tty
    COLORFGBG="15;0" $GUM choose "$@" >"$_GUM_TMP"
    drain_tty
    cat "$_GUM_TMP"
}

# ── Header ────────────────────────────────────────────────────────────────────
clear
$GUM style \
    --border rounded \
    --border-foreground 99 \
    --padding "0 2" \
    --bold \
    --foreground 99 \
    "Loc Audio — Setup"
echo ""

# ── Check loc-guard dispatcher is installed ───────────────────────────────────
if [[ ! -d "$INSTALL_DIR/hooks" ]]; then
    err "loc-guard hooks not found — run loc-guard/bootstrap.sh first"
    exit 1
fi

# ── Read locations from hooks dir ─────────────────────────────────────────────
LOCATIONS=()
for d in "$INSTALL_DIR/hooks"/*/; do
    [[ -d "$d" ]] && LOCATIONS+=("$(basename "$d")")
done

if [[ ${#LOCATIONS[@]} -eq 0 ]]; then
    err "No locations found — run loc-guard/bootstrap.sh first"
    exit 1
fi

ok "Found locations: ${LOCATIONS[*]}"
echo ""

# ── SwitchAudioSource ─────────────────────────────────────────────────────────
if ! command -v SwitchAudioSource &>/dev/null; then
    warn "SwitchAudioSource not found (needed for device switching)"
    if $GUM confirm "Install via Homebrew?"; then
        $GUM spin --spinner dot --title "Installing SwitchAudioSource..." -- brew install switchaudio-osx
        ok "SwitchAudioSource installed"
    else
        warn "Skipping — only volume control will work, not device switching"
    fi
fi

# ── Get available output devices ──────────────────────────────────────────────
DEVICES=()
if command -v SwitchAudioSource &>/dev/null; then
    while IFS= read -r dev; do
        [[ -n "$dev" ]] && DEVICES+=("$dev")
    done < <(SwitchAudioSource -a -t output 2>/dev/null)
fi

# ── Per-location audio config ─────────────────────────────────────────────────
$GUM style --foreground 212 --bold "── Audio per Location"
echo ""

declare -A LOC_DEVICE LOC_VOLUME

VOLUME_OPTIONS=("100" "75" "50" "25" "0 (mute)" "Skip")

for loc in "${LOCATIONS[@]}"; do
    printf '\033[38;5;99m\033[1m┌─ %s ─┐\033[0m\n' "$loc"
    echo ""

    # Device
    if [[ ${#DEVICES[@]} -gt 0 ]]; then
        DEVICE=$(choose_one "Output device for $loc:" "Skip" "${DEVICES[@]}")
        if [[ "$DEVICE" == "Skip" ]]; then
            LOC_DEVICE[$loc]=""
            info "Device: unchanged"
        else
            LOC_DEVICE[$loc]="$DEVICE"
            ok "Device: $DEVICE"
        fi
    else
        LOC_DEVICE[$loc]=""
        info "Device switching unavailable"
    fi

    echo ""

    # Volume
    VOL=$(choose_one "Volume for $loc:" "${VOLUME_OPTIONS[@]}")
    if [[ "$VOL" == "Skip" ]]; then
        LOC_VOLUME[$loc]=""
        info "Volume: unchanged"
    elif [[ "$VOL" == "0 (mute)" ]]; then
        LOC_VOLUME[$loc]="0"
        ok "Volume: muted"
    else
        LOC_VOLUME[$loc]="$VOL"
        ok "Volume: $VOL%"
    fi

    echo ""
done

# ── Write audio.conf ──────────────────────────────────────────────────────────
{
echo "# Audio settings — generated by loc-audio/bootstrap.sh"
echo "# Edit this file to adjust settings. Changes take effect on next location switch."
echo ""
for loc in "${LOCATIONS[@]}"; do
    KEY=$(echo "$loc" | tr '[:lower:]' '[:upper:]' | tr ' ' '_')
    echo "# ── $loc"
    echo "${KEY}_device=\"${LOC_DEVICE[$loc]}\""
    echo "${KEY}_volume=\"${LOC_VOLUME[$loc]}\""
    echo ""
done
} > "$INSTALL_DIR/audio.conf"
ok "audio.conf"

# ── Install apply script ──────────────────────────────────────────────────────
cp "$ADDON_DIR/scripts/apply.sh" "$INSTALL_DIR/audio-apply.sh"
chmod +x "$INSTALL_DIR/audio-apply.sh"
ok "audio-apply.sh"

# ── Install hooks ─────────────────────────────────────────────────────────────
for loc in "${LOCATIONS[@]}"; do
    mkdir -p "$INSTALL_DIR/hooks/$loc"
    cat > "$INSTALL_DIR/hooks/$loc/03-audio" << 'HOOK'
#!/usr/bin/env bash
exec 2>&1
"$HOME/.wifi-loc-control/audio-apply.sh" "$1"
HOOK
    chmod +x "$INSTALL_DIR/hooks/$loc/03-audio"
    ok "Hook: $loc"
done

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
$GUM style \
    --border rounded \
    --border-foreground 2 \
    --padding "1 4" \
    --bold \
    --foreground 2 \
    "Loc Audio installed!"
echo ""
$GUM style --bold "To adjust settings:"
$GUM style --faint "  Edit ~/.wifi-loc-control/audio.conf"
echo ""
