#!/opt/homebrew/bin/bash
set -e

ADDON_DIR="$(cd "$(dirname "$0")" && pwd)"
INSTALL_DIR="$HOME/.wifi-loc-control"

# ── gum ───────────────────────────────────────────────────────────────────────
if ! command -v gum &>/dev/null; then
    echo "Installing gum..."
    brew install gum
fi
GUM=$(which gum)

ok()   { $GUM style --foreground 2   "✓ $*"; }
warn() { $GUM style --foreground 214 "⚠ $*"; }
err()  { $GUM style --foreground 1   "✗ $*"; }
info() { $GUM style --foreground 12  "→ $*"; }

# ── Header ────────────────────────────────────────────────────────────────────
clear
$GUM style \
    --border rounded \
    --border-foreground 99 \
    --padding "0 2" \
    --bold \
    --foreground 99 \
    "Loc Wallpaper — Setup"
echo ""

# ── Check loc-guard dispatcher is installed ───────────────────────────────────
if [[ ! -d "$INSTALL_DIR/hooks" ]]; then
    err "loc-guard hooks not found — run loc-guard/bootstrap.sh first"
    exit 1
fi

# ── Read locations from hooks dir ─────────────────────────────────────────────
LOCATIONS=()
for d in "$INSTALL_DIR/hooks"/*/; do
    [[ -d "$d" ]] && LOCATIONS+=("$(basename "$d")")
done

if [[ ${#LOCATIONS[@]} -eq 0 ]]; then
    err "No locations found — run loc-guard/bootstrap.sh first"
    exit 1
fi

ok "Found locations: ${LOCATIONS[*]}"
echo ""

# ── Per-location wallpaper ────────────────────────────────────────────────────
$GUM style --foreground 212 --bold "── Wallpaper per Location"
$GUM style --faint "A file picker will open for each location. Cancel to skip."
echo ""

declare -A LOC_WALLPAPER

for loc in "${LOCATIONS[@]}"; do
    printf '\033[38;5;99m\033[1m┌─ %s ─┐\033[0m\n' "$loc"
    echo ""
    info "Opening file picker for $loc..."
    path=$(osascript -e "POSIX path of (choose file with prompt \"Select wallpaper for $loc:\" of type {\"public.image\"})" 2>/dev/null || true)
    path="${path%$'\n'}"
    if [[ -n "$path" ]]; then
        ok "$path"
    else
        info "Skipped"
    fi
    LOC_WALLPAPER[$loc]="$path"
    echo ""
done

# ── Write wallpaper.conf ──────────────────────────────────────────────────────
{
echo "# Wallpaper settings — generated by loc-wallpaper/bootstrap.sh"
echo "# Edit this file to change wallpapers. Changes take effect on next location switch."
echo ""
for loc in "${LOCATIONS[@]}"; do
    KEY=$(echo "$loc" | tr '[:lower:]' '[:upper:]' | tr ' ' '_')
    echo "${KEY}_wallpaper=\"${LOC_WALLPAPER[$loc]}\""
done
} > "$INSTALL_DIR/wallpaper.conf"
ok "wallpaper.conf"

# ── Install apply script ──────────────────────────────────────────────────────
cp "$ADDON_DIR/scripts/apply.sh" "$INSTALL_DIR/wallpaper-apply.sh"
chmod +x "$INSTALL_DIR/wallpaper-apply.sh"
ok "wallpaper-apply.sh"

# ── Install hooks ─────────────────────────────────────────────────────────────
for loc in "${LOCATIONS[@]}"; do
    mkdir -p "$INSTALL_DIR/hooks/$loc"
    cat > "$INSTALL_DIR/hooks/$loc/02-wallpaper" << 'HOOK'
#!/usr/bin/env bash
exec 2>&1
"$HOME/.wifi-loc-control/wallpaper-apply.sh" "$1"
HOOK
    chmod +x "$INSTALL_DIR/hooks/$loc/02-wallpaper"
    ok "Hook: $loc"
done

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
$GUM style \
    --border rounded \
    --border-foreground 2 \
    --padding "1 4" \
    --bold \
    --foreground 2 \
    "Loc Wallpaper installed!"
echo ""
$GUM style --bold "To change wallpapers:"
$GUM style --faint "  Edit ~/.wifi-loc-control/wallpaper.conf"
echo ""
