#!/opt/homebrew/bin/bash
set -e

ADDON_DIR="$(cd "$(dirname "$0")" && pwd)"
INSTALL_DIR="$HOME/.wifi-loc-control"

# ── gum ───────────────────────────────────────────────────────────────────────
if ! command -v gum &>/dev/null; then
    echo "Installing gum..."
    brew install gum
fi
GUM=$(which gum)

ok()   { $GUM style --foreground 2   "✓ $*"; }
warn() { $GUM style --foreground 214 "⚠ $*"; }
err()  { $GUM style --foreground 1   "✗ $*"; }
info() { $GUM style --foreground 12  "→ $*"; }

_GUM_TMP=$(mktemp)
trap 'rm -f "$_GUM_TMP"' EXIT

drain_tty() {
    stty -echo </dev/tty 2>/dev/null
    sleep 0.3
    while IFS= read -r -t 0.1 -n 1 _d </dev/tty 2>/dev/null; do :; done
    stty echo </dev/tty 2>/dev/null
}

choose_one() {
    local prompt="$1"; shift
    [[ -n "$prompt" ]] && printf '\033[38;5;212m%s\033[0m\n' "$prompt" >/dev/tty
    drain_tty
    COLORFGBG="15;0" $GUM choose "$@" >"$_GUM_TMP"
    drain_tty
    cat "$_GUM_TMP"
}

# ── Header ────────────────────────────────────────────────────────────────────
clear
$GUM style \
    --border rounded \
    --border-foreground 99 \
    --padding "0 2" \
    --bold \
    --foreground 99 \
    "Loc Display — Setup"
echo ""

# ── Ensure hook dispatcher is installed ──────────────────────────────────────
source "$ADDON_DIR/../lib/setup-dispatcher.sh"
if ! setup_dispatcher; then
    err "Could not set up hook dispatcher"
    exit 1
fi

# ── Read locations from hooks dir ─────────────────────────────────────────────
LOCATIONS=()
for d in "$INSTALL_DIR/hooks"/*/; do
    [[ -d "$d" ]] && LOCATIONS+=("$(basename "$d")")
done

if [[ ${#LOCATIONS[@]} -eq 0 ]]; then
    err "No locations found"
    exit 1
fi

ok "Found locations: ${LOCATIONS[*]}"
echo ""

# ── brightness CLI ────────────────────────────────────────────────────────────
if ! command -v brightness &>/dev/null; then
    warn "brightness not found (needed for brightness control)"
    if $GUM confirm "Install via Homebrew?"; then
        $GUM spin --spinner dot --title "Installing brightness..." -- brew install brightness
        ok "brightness installed"
    else
        warn "Skipping — only Night Shift control will work"
    fi
fi

# ── Per-location display config ───────────────────────────────────────────────
$GUM style --foreground 212 --bold "── Display per Location"
echo ""

declare -A LOC_BRIGHTNESS LOC_NIGHT_SHIFT

BRIGHTNESS_OPTIONS=("100" "75" "50" "25" "10" "Skip")
NIGHT_SHIFT_OPTIONS=("On" "Off" "Skip")

for loc in "${LOCATIONS[@]}"; do
    printf '\033[38;5;99m\033[1m┌─ %s ─┐\033[0m\n' "$loc"
    echo ""

    # Brightness
    if command -v brightness &>/dev/null; then
        BRI=$(choose_one "Brightness for $loc:" "${BRIGHTNESS_OPTIONS[@]}")
        if [[ "$BRI" == "Skip" ]]; then
            LOC_BRIGHTNESS[$loc]=""
            info "Brightness: unchanged"
        else
            LOC_BRIGHTNESS[$loc]="$BRI"
            ok "Brightness: $BRI%"
        fi
    else
        LOC_BRIGHTNESS[$loc]=""
        info "Brightness control unavailable"
    fi

    echo ""

    # Night Shift
    NS=$(choose_one "Night Shift for $loc:" "${NIGHT_SHIFT_OPTIONS[@]}")
    if [[ "$NS" == "Skip" ]]; then
        LOC_NIGHT_SHIFT[$loc]=""
        info "Night Shift: unchanged"
    else
        LOC_NIGHT_SHIFT[$loc]="$(echo "$NS" | tr '[:upper:]' '[:lower:]')"
        ok "Night Shift: $NS"
    fi

    echo ""
done

# ── Write display.conf ────────────────────────────────────────────────────────
{
echo "# Display settings — generated by loc-display/bootstrap.sh"
echo "# Edit this file to adjust settings. Changes take effect on next location switch."
echo ""
for loc in "${LOCATIONS[@]}"; do
    KEY=$(echo "$loc" | tr '[:lower:]' '[:upper:]' | tr ' ' '_')
    echo "# ── $loc"
    echo "${KEY}_brightness=\"${LOC_BRIGHTNESS[$loc]}\""
    echo "${KEY}_night_shift=\"${LOC_NIGHT_SHIFT[$loc]}\""
    echo ""
done
} > "$INSTALL_DIR/display.conf"
ok "display.conf"

# ── Install apply script ──────────────────────────────────────────────────────
cp "$ADDON_DIR/scripts/apply.sh" "$INSTALL_DIR/display-apply.sh"
chmod +x "$INSTALL_DIR/display-apply.sh"
ok "display-apply.sh"

# ── Install hooks ─────────────────────────────────────────────────────────────
for loc in "${LOCATIONS[@]}"; do
    mkdir -p "$INSTALL_DIR/hooks/$loc"
    cat > "$INSTALL_DIR/hooks/$loc/04-display" << 'HOOK'
#!/usr/bin/env bash
exec 2>&1
"$HOME/.wifi-loc-control/display-apply.sh" "$1"
HOOK
    chmod +x "$INSTALL_DIR/hooks/$loc/04-display"
    ok "Hook: $loc"
done

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
$GUM style \
    --border rounded \
    --border-foreground 2 \
    --padding "1 4" \
    --bold \
    --foreground 2 \
    "Loc Display installed!"
echo ""
$GUM style --bold "To adjust settings:"
$GUM style --faint "  Edit ~/.wifi-loc-control/display.conf"
echo ""
